version: '3.8'
services:
  main:
    container_name: main
    build:
      context: .
      target: development
    image: 'bp_main'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
      PORT: ${PORT}
    depends_on:
      - postgres
    links:
      - postgres
    restart: always
    volumes:
      - .:/michal/src/api
    command: npm run start:dev
    env_file:
      - .env
    ports:
      - "8000:3000"

  postgres:
    container_name: 'bp_postgres'
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    image: postgres:13.2
    ports:
      - 5432:5432
    volumes: 
      - ./data/bp:/var/lib/postgresql/data